sudo: false  # Use container-based infrastructure
language: python
python:
  - "2.7"
  - "3.6"
cache:
  pip: true
  # cache directory used for Ensembl downloads of GTF and FASTA files
  # along with the indexed db of intervals and ID mappings and pickles
  # of sequence dictionaries. Also, pip
  directories:
    - $HOME/.cache/pyensembl/
    - $HOME/.cache/pyensembl/GRCh37/ensembl75/
    - $HOME/miniconda
addons:
  apt:
    packages:
      # Needed for NetMHC
      - tcsh
before_install:
  # don't install miniconda if it's already cached
  # if not yet installed, use different versions for py2 vs. py3
  - |
    if [ -f  $HOME/miniconda/bin ];
      then
      echo "miniconda already installed"
    else
      rm -rf $HOME/miniconda
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
    fi
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - python --version
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      numpy nose pandas cython pandoc
  - source activate test-environment
  - pip install pypandoc
  - pip install .
  - pip install coveralls
  - pyensembl install --release 75 --species human
script:
  - nosetests test --with-coverage --cover-package=varlens
after_success:
  coveralls
deploy:
  provider: pypi
  user: openvax
  distributions: sdist
  password:
    secure: "jzb1g5AroLPBzPxWWwcVTfUE6/T1d6q2EP7ePhWIKOnVJxHZNkmTztMKcX0MtfpJ2m/tYolNU/UBeDrwX2QuHMyIJmZIU66NpKNtRU8XSKaquKGTofV4Y82RcFzkCKFtBnh280uU2prqfzp75XWb10CMoiK+wPyn948BxpCVi1Mhm1+MA+qolE7lFVI4QLehyT4UZWA/LzdpinML8MsQ65xFFH+st9RHX4Gm3dQeRcnM/QiCGqYsJzU6MK6czsIAuRuqN57JzNdbynhqv//iVK2ixKomVvaJSYMt+f+gh327zbBRCGyHgHlEzE1ZrqnqJmGB+0LiqpE9Vvg0r2lAqXgxhHjPoO59Yo+2bRxcPF7hB6F6hG4mNJBrQXo2Ny88RpviWT5JrO6pUCePHdTrddJdFcURlVPBEXVzgmp8Az8CKa3YyZFB43XLwqwAkCD7HjPlyDHS9xEaxfp+B0PgwnYq63QDA5WKCSgCanmW7bLx0B4UZkkG1SIv/FtP40nAnG7i3XMHqlV0kq1yPJXMZJUH5t48YxGKFqjC1VeU9Qm2zaKlVXazK6OQxW0I0S1LNKosHwcq+uS5442/hgaeL5v13YKjExzCM8YmQwuBGtahjh4TcDdNG9isTx/atl/pDRR/EE8jXTxc4m8Ewj2rkfWN+YDu1jWiidUOcIn2qZA="
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
